module.exports = {
   "22888": {
      "name": "Rallying Cry of the Dragonslayer",
      "desc": "Dragonslayer",
      "type": "World",
      "score": 200,
      "onetime": true,
   },
   "15366": {
      "name": "Songflower Serenade",
      "desc": "Songflower",
      "type": "World",
      "score": 600,
      "onetime": true,
   },
   "22817": {
      "name": "Fengus' Ferocity",
      "desc": "DMT AP",
      "type": "World",
      "score": 200,
      "ignore": ["Mage", "Warlock", "Shaman", "Priest"],
      "onetime": true,
   },
   "22820": {
      "name": "Slip'kik's Savvy",
      "desc": "DMT Spell Crit",
      "type": "World",
      "score": 200,
      "onetime": true,
      "ignore": ["Warrior", "Rogue", "Hunter"],
   },
   "22818": {
      "name": "Mol'dar's Moxie",
      "desc": "DMT Stamina",
      "type": "World",
      "score": 200,
      "onetime": true,
   },
   "3593": {
      "name": "Health II (120 HP)",
      "desc": "Elixir of Fortitude",
      "type": "Consumable",
      "score": 2,
   },
   "3222": {
      "name": "Regeneration (6 hp5)",
      "desc": "Strong Troll's Blood Potion",
      "type": "Consumable",
      "score": 1,
   },
   "3223": {
      "name": "Regeneration (12 hp5)",
      "desc": "Mighty Troll's Blood Potion",
      "type": "Consumable",
      "score": 2,
   },
   "24361": {
      "name": "Regeneration (20 hp5)",
      "desc": "Major Troll's Blood Potion",
      "type": "Consumable",
      "score": 3,
   },
   "24363": {
      "name": "Mana Regeneration (12 mp5)",
      "desc": "Mageblood Potion",
      "type": "Consumable",
      "score": 5,
   },
   "17543": {
      "name": "Greater Fire Protection",
      "desc": "Greater Fire Protection Potion",
      "type": "Consumable",
      "score": 600,
      "onetime": true,
   },
   "17549": {
      "name": "Greater Arcane Protection",
      "desc": "Greater Arcane Protection Potion",
      "type": "Consumable",
      "score": 600,
      "onetime": true,
   },
   "7233": {
      "name": "Fire Protection",
      "type": "Consumable",
      "score": 200,
      "onetime": true,
   },
   "17548": {
      "name": "Greater Shadow Protection",
      "desc": "Greater Shadow Protection Potion",
      "type": "Consumable",
      "score": 600,
      "onetime": true,
   },
   "7242": {
      "name": "Shadow Protection",
      "desc": "Shadow Protection Potion",
      "type": "Consumable",
      "score": 200,
      "onetime": true,
   },
   "17546": {
      "name": "Greater Nature Protection",
      "desc": "Greater Nature Protection Potion",
      "type": "Consumable",
      "score": 600,
      "onetime": true,
   },
   "7254": {
      "name": "Nature Protection",
      "desc": "Nature Protection Potion",
      "type": "Consumable",
      "score": 200,
      "onetime": true,
   },
   "17544": {
      "name": "Greater Frost Protection",
      "desc": "Greater Frost Protection Potion",
      "type": "Consumable",
      "score": 200,
      "onetime": true,
   },
   "7239": {
      "name": "Frost Protection",
      "desc": "Frost Protection Potion",
      "type": "Consumable",
      "score": 100,
      "onetime": true,
   },
   "17539": {
      "name": "Greater Arcane Elixir",
      "type": "Consumable",
      "score": 5,
      "ignore": ["Warrior", "Rogue", "Hunter"],
   },
   "11474": {
      "name": "Elixir of Shadow Power",
      "type": "Consumable",
      "score": 5,
      "ignore": ["Mage", "Shaman"],
   },
   "17538": {
      "name": "Elixir of the Mongoose",
      "type": "Consumable",
      "score": 5,
      "ignore": ["Mage", "Warlock", "Shaman", "Priest"],
   },
   "11405": {
      "name": "Elixir of the Giants",
      "type": "Consumable",
      "score": 5,
      "ignore": ["Mage", "Warlock", "Shaman", "Priest"],
   },
   "16326": {
      "name": "Juju Ember",
      "desc": "Fire Res Juju",
      "type": "Consumable",
      "score": 5,
   },
   "16329": {
      "name": "Juju Might",
      "desc": "Attack Power Juju",
      "type": "Consumable",
      "score": 5,
      "ignore": ["Mage", "Warlock", "Shaman", "Priest"],
   },
   "16323": {
      "name": "Juju Power",
      "desc": "Strength Juju",
      "type": "Consumable",
      "score": 5,
      "ignore": ["Mage", "Warlock", "Shaman", "Priest"],
   },
   "16322": {
      "name": "Juju Flurry",
      "desc": "Attack Speed Juju",
      "type": "Consumable",
      "score": 5,
      "ignore": ["Mage", "Warlock", "Shaman", "Priest"],
   },
   "16325": {
      "name": "Juju Chill",
      "desc": "Frost Res Juju",
      "type": "Consumable",
      "score": 1,
   },
   "16321": {
      "name": "Juju Escape",
      "desc": "Dodge Juju",
      "type": "Consumable",
      "score": 5,
      "ignore": ["Mage", "Warlock", "Shaman", "Priest"],
   },
   "17628": {
      "name": "Supreme Power",
      "type": "Flask",
      "score": 2000,
      "onetime": true,
   },
   "17626": {
      "name": "Flask of the Titans",
      "type": "Flask",
      "score": 2000,
      "onetime": true,
   },
   "17627": {
      "name": "Distilled Wisdom",
      "type": "Flask",
      "score": 2000,
      "onetime": true,
   },
   "24870": {
      "name": "Well Fed (?? sta, ?? spi)",
      "type": "Food",
      "score": 5,
   },
   "19705": {
      "name": "Well Fed (1 sta, 1 spi)",
      "type": "Food",
      "score": 5,
   },
   "19706": {
      "name": "Well Fed (3 sta, 3 spi)",
      "type": "Food",
      "score": 5,
   },
   "19709": {
      "name": "Well Fed (7 sta, 7 spi)",
      "type": "Food",
      "score": 5,
   },
   "19710": {
      "name": "Well Fed (11 sta, 11 spi)",
      "type": "Food",
      "score": 5,
   },
   "19711": {
      "name": "Well Fed (13 sta, 13 spi)",
      "type": "Food",
      "score": 5,
   },
   "25694": {
      "name": "Well Fed (2 mp5)",
      "type": "Food",
      "score": 5,
      "ignore": ["Warrior", "Rogue"]
   },
   "25941": {
      "name": "Well Fed (5 mp5)",
      "type": "Food",
      "score": 5,
      "ignore": ["Warrior", "Rogue"]
   },
   "18194": {
      "name": "Mana Regeneration (7 mp5)",
      "desc": "Nightfin Soup",
      "type": "Food",
      "score": 5,
      "ignore": ["Warrior", "Rogue"]
   },
   "22730": {
      "name": "Increased Intellect (9 int)",
      "desc": "Runn Tum Tuber Surprise",
      "type": "Food",
      "score": 5,
      "ignore": ["Warrior", "Rogue"]
   },
   "18192": {
      "name": "Increased Agility (9 agi)",
      "desc": "Grilled Squid",
      "type": "Food",
      "score": 5,
      "ignore": ["Mage", "Warlock", "Priest"],
   },
   "24799": {
      "name": "Well Fed (19 str)",
      "desc": "Smoked Desert Dumpling",
      "type": "Food",
      "score": 5,
      "ignore": ["Mage", "Warlock", "Priest", "Shaman", "Hunter"],
   },
   "18284": {
      "name": "Gordok Green Grog (9 sta)",
      "desc": "DMT beer",
      "type": "Alcohol",
      "score": 5,
   },
   "22790": {
      "name": "Kreeg's Stout Beatdown (25 spi, -5 int)",
      "desc": "DMT beer",
      "type": "Alcohol",
      "score": 5,
   },
   "25804": {
      "name": "Rumsey Rum Black Label (15 sta)",
      "desc": "Fishing",
      "type": "Alcohol",
      "score": 5,
   },
}