module.exports = {
   "22888": {
      "name": "Rallying Cry of the Dragonslayer",
      "desc": "Dragonslayer",
      "type": "World",
      "score": 200,
      "onetime": true,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_misc_head_dragon_01.jpg",
   },
   "15366": {
      "name": "Songflower Serenade",
      "desc": "Songflower",
      "type": "World",
      "score": 600,
      "onetime": true,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/spell_holy_mindvision.jpg",
   },
   "22817": {
      "name": "Fengus' Ferocity",
      "desc": "DMT AP",
      "type": "World",
      "score": 200,
      "ignore": ["Mage", "Warlock", "Shaman", "Priest"],
      "onetime": true,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/spell_nature_undyingstrength.jpg",
   },
   "22820": {
      "name": "Slip'kik's Savvy",
      "desc": "DMT Spell Crit",
      "type": "World",
      "score": 200,
      "onetime": true,
      "ignore": ["Warrior", "Rogue", "Hunter"],
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/spell_holy_lesserheal02.jpg",
   },
   "22818": {
      "name": "Mol'dar's Moxie",
      "desc": "DMT Stamina",
      "type": "World",
      "score": 200,
      "onetime": true,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/spell_nature_massteleport.jpg",
   },
   "3593": {
      "name": "Health II (120 HP)",
      "desc": "Elixir of Fortitude",
      "type": "Consumable",
      "score": 2,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_potion_43.jpg",
   },
   "3222": {
      "name": "Regeneration (6 hp5)",
      "desc": "Strong Troll's Blood Potion",
      "type": "Consumable",
      "score": 1,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_potion_79.jpg",
   },
   "3223": {
      "name": "Regeneration (12 hp5)",
      "desc": "Mighty Troll's Blood Potion",
      "type": "Consumable",
      "score": 2,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_potion_79.jpg",
   },
   "24361": {
      "name": "Regeneration (20 hp5)",
      "desc": "Major Troll's Blood Potion",
      "type": "Consumable",
      "score": 3,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_potion_80.jpg",
   },
   "24363": {
      "name": "Mana Regeneration (12 mp5)",
      "desc": "Mageblood Potion",
      "type": "Consumable",
      "score": 5,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_potion_45.jpg",
   },
   "17543": {
      "name": "Greater Fire Protection",
      "desc": "Greater Fire Protection Potion",
      "type": "Consumable",
      "score": 600,
      "onetime": true,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_potion_24.jpg",
   },
   "17549": {
      "name": "Greater Arcane Protection",
      "desc": "Greater Arcane Protection Potion",
      "type": "Consumable",
      "score": 600,
      "onetime": true,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_potion_83.jpg",
   },
   "7233": {
      "name": "Fire Protection",
      "type": "Consumable",
      "score": 200,
      "onetime": true,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_potion_16.jpg",
   },
   "17548": {
      "name": "Greater Shadow Protection",
      "desc": "Greater Shadow Protection Potion",
      "type": "Consumable",
      "score": 600,
      "onetime": true,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_potion_23.jpg",
   },
   "7242": {
      "name": "Shadow Protection",
      "desc": "Shadow Protection Potion",
      "type": "Consumable",
      "score": 200,
      "onetime": true,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_potion_44.jpg",
   },
   "17546": {
      "name": "Greater Nature Protection",
      "desc": "Greater Nature Protection Potion",
      "type": "Consumable",
      "score": 600,
      "onetime": true,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_potion_22.jpg",
   },
   "7254": {
      "name": "Nature Protection",
      "desc": "Nature Protection Potion",
      "type": "Consumable",
      "score": 200,
      "onetime": true,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_potion_06.jpg",
   },
   "17544": {
      "name": "Greater Frost Protection",
      "desc": "Greater Frost Protection Potion",
      "type": "Consumable",
      "score": 200,
      "onetime": true,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_potion_20.jpg",
   },
   "7239": {
      "name": "Frost Protection",
      "desc": "Frost Protection Potion",
      "type": "Consumable",
      "score": 100,
      "onetime": true,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_potion_13.jpg",
   },
   "17539": {
      "name": "Greater Arcane Elixir",
      "type": "Consumable",
      "score": 5,
      "ignore": ["Warrior", "Rogue", "Hunter"],
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_potion_25.jpg",
   },
   "11474": {
      "name": "Elixir of Shadow Power",
      "type": "Consumable",
      "score": 5,
      "ignore": ["Mage", "Shaman", "Warrior", "Rogue", "Hunter", "Druid"],
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_potion_46.jpg",
   },
   "17538": {
      "name": "Elixir of the Mongoose",
      "type": "Consumable",
      "score": 5,
      "ignore": ["Mage", "Warlock", "Shaman", "Priest"],
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_potion_32.jpg",
   },
   "11405": {
      "name": "Elixir of the Giants",
      "type": "Consumable",
      "score": 5,
      "ignore": ["Mage", "Warlock", "Shaman", "Priest"],
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_potion_61.jpg",
   },
   "16326": {
      "name": "Juju Ember",
      "desc": "Fire Res Juju",
      "type": "Consumable",
      "score": 5,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_misc_monsterscales_15.jpg",
   },
   "16329": {
      "name": "Juju Might",
      "desc": "Attack Power Juju",
      "type": "Consumable",
      "score": 5,
      "ignore": ["Mage", "Warlock", "Shaman", "Priest"],
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_misc_monsterscales_07.jpg",
   },
   "16323": {
      "name": "Juju Power",
      "desc": "Strength Juju",
      "type": "Consumable",
      "score": 5,
      "ignore": ["Mage", "Warlock", "Shaman", "Priest"],
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_misc_monsterscales_11.jpg",
   },
   "16322": {
      "name": "Juju Flurry",
      "desc": "Attack Speed Juju",
      "type": "Consumable",
      "score": 5,
      "ignore": ["Mage", "Warlock", "Shaman", "Priest"],
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_misc_monsterscales_17.jpg",
   },
   "16325": {
      "name": "Juju Chill",
      "desc": "Frost Res Juju",
      "type": "Consumable",
      "score": 1,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_misc_monsterscales_09.jpg",
   },
   "16321": {
      "name": "Juju Escape",
      "desc": "Dodge Juju",
      "type": "Consumable",
      "score": 5,
      "ignore": ["Mage", "Warlock", "Shaman", "Priest"],
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_misc_monsterscales_17.jpg",
   },
   "17628": {
      "name": "Supreme Power",
      "type": "Flask",
      "score": 2000,
      "onetime": true,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_potion_41.jpg",
   },
   "17626": {
      "name": "Flask of the Titans",
      "type": "Flask",
      "score": 2000,
      "onetime": true,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_potion_62.jpg",
   },
   "17627": {
      "name": "Distilled Wisdom",
      "type": "Flask",
      "score": 2000,
      "onetime": true,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_potion_97.jpg",
   },
   "24870": {
      "name": "Well Fed (?? sta, ?? spi)",
      "type": "Food",
      "score": 5,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/spell_misc_food.jpg",
   },
   "19705": {
      "name": "Well Fed (1 sta, 1 spi)",
      "type": "Food",
      "score": 5,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_drink_04.jpg",
   },
   "19706": {
      "name": "Well Fed (3 sta, 3 spi)",
      "type": "Food",
      "score": 5,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_misc_food_47.jpg",
   },
   "19709": {
      "name": "Well Fed (7 sta, 7 spi)",
      "type": "Food",
      "score": 5,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_misc_food_18.jpg",
   },
   "19710": {
      "name": "Well Fed (11 sta, 11 spi)",
      "type": "Food",
      "score": 5,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_misc_shell_03.jpg",
   },
   "19711": {
      "name": "Well Fed (13 sta, 13 spi)",
      "type": "Food",
      "score": 5,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_misc_fish_21.jpg",
   },
   "25694": {
      "name": "Well Fed (2 mp5)",
      "type": "Food",
      "score": 5,
      "ignore": ["Warrior", "Rogue"],
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_misc_fish_21.jpg",
   },
   "25941": {
      "name": "Well Fed (5 mp5)",
      "type": "Food",
      "score": 5,
      "ignore": ["Warrior", "Rogue"],
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_misc_fish_21.jpg",
   },
   "18194": {
      "name": "Mana Regeneration (7 mp5)",
      "desc": "Nightfin Soup",
      "type": "Food",
      "score": 5,
      "ignore": ["Warrior", "Rogue"],
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/spell_nature_manaregentotem.jpg",
   },
   "22730": {
      "name": "Increased Intellect (9 int)",
      "desc": "Runn Tum Tuber Surprise",
      "type": "Food",
      "score": 5,
      "ignore": ["Warrior", "Rogue"],
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_misc_organ_03.jpg",
   },
   "18192": {
      "name": "Increased Agility (9 agi)",
      "desc": "Grilled Squid",
      "type": "Food",
      "score": 5,
      "ignore": ["Mage", "Warlock", "Priest"],
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_gauntlets_19.jpg",
   },
   "24799": {
      "name": "Well Fed (19 str)",
      "desc": "Smoked Desert Dumpling",
      "type": "Food",
      "score": 5,
      "ignore": ["Mage", "Warlock", "Priest", "Shaman", "Hunter"],
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_misc_food_64.jpg",
   },
   "22789": {
      "name": "Gordok Green Grog (10 sta)",
      "desc": "DMT beer",
      "type": "Alcohol",
      "score": 5,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_drink_03.jpg",
   },
   "22790": {
      "name": "Kreeg's Stout Beatdown (25 spi, -5 int)",
      "desc": "DMT beer",
      "type": "Alcohol",
      "score": 5,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_drink_05.jpg",
   },
   "25804": {
      "name": "Rumsey Rum Black Label (15 sta)",
      "desc": "Fishing",
      "type": "Alcohol",
      "score": 5,
      "imageUrl": "https://wow.zamimg.com/images/wow/icons/large/inv_drink_04.jpg",
   },
}